packages:
  - apps/*
  - facades/*
  - libs/*
  - tools/*

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@just-web/*'
  - '@repobuddy/*'